### PR TITLE
Fix loading defaults from image object def

### LINKED ISSUE #1658: `/image` subclasses don't have vars set
```
/image/foreground_parallax_occlusion_overlay
	icon = 'icons/mob.dmi'
	icon_state = "mob"
	plane = PLANE_FOREGROUND_PARALLAX_OCCLUSION
```

`var/image/test = new /image/foreground_parallax_occlusion_overlay` should result in an image with `icon == 'icons/mob.dmi'` and `icon_state == "mob"` etc, but does not. Instead you get basically a `new /image` with no vars set

breaks parallax occlusion on goon, and probably a bunch of overlay bugs across SS13

here's a failing test about it:
```
/image/subclass
	plane = 123
	icon_state = "subclass"

/proc/RunTest()
	var/image/test = new /image/subclass
	ASSERT(test.plane == 123)
	ASSERT(test.icon_state == "subclass")
```

### PR DESCRIPTION
**Pull request by amylizzle**
Fixes #1658

### CODE REVIEW

File: OpenDreamRuntime/Objects/Types/DreamObjectImage.cs [hunk 1]
```diff
@@ -37,14 +37,14 @@ public sealed class DreamObjectImage : DreamObject {
 
     public override void Initialize(DreamProcArguments args) {
         base.Initialize(args);
+        Appearance = AtomManager.GetAppearanceFromDefinition(ObjectDefinition);
```
Comment (wixoaGit) [inline OpenDreamRuntime/Objects/Types/DreamObjectImage.cs:40]: Would be good to avoid the `AtomManager.GetAppearanceFromDefinition()` if possible. Wouldn't we get the same behavior if the below `if` was kept the same but `Appearance = new IconAppearance()` was replaced with this?

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: OpenDreamRuntime/Objects/Types/DreamObjectImage.cs (hunk 1 above)
Comment (amylizzle) [reply OpenDreamRuntime/Objects/Types/DreamObjectImage.cs:40]: Any particular reason to avoid `AtomManager.GetAppearanceFromDefinition()`? It seems like the only sensible thing to do would be to duplicate its code anyway.

Comment (wixoaGit) [reply OpenDreamRuntime/Objects/Types/DreamObjectImage.cs:40]: I'm not saying to avoid it entirely, but only use it if there was no argument given to copy the appearance from.

Appearance creation is slow/heavy so it's good to avoid it if it's never used. Even if it's cached that's an extra unnecessary dictionary hit in what I imagine to be somewhat hot code.

File: DMCompiler/DMStandard/Types/Image.dm [hunk 2]
```diff
@@ -7,8 +7,11 @@
 	var/appearance_flags = 0
 	var/blend_mode = 0
 	var/color = null
+	var/contents as opendream_unimplemented
```
Comment (wixoaGit) [inline DMCompiler/DMStandard/Types/Image.dm:10]:
```suggestion
	var/list/contents as opendream_unimplemented
```

File: DMCompiler/DMStandard/Types/Image.dm [hunk 3]
```diff
@@ -39,6 +43,8 @@
 	var/text = "i" as opendream_unimplemented
 	var/matrix/transform
 	var/list/underlays = null
+	var/verbs as opendream_unimplemented
```
Comment (wixoaGit) [inline DMCompiler/DMStandard/Types/Image.dm:46]:
```suggestion
	var/list/verbs as opendream_unimplemented
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]

**Review by wixoaGit — APPROVED** [review]
