### PR TITLE
Make the `in` operator greedy

### LINKED ISSUE #1958: Opendream fails to parse expression
Opendream chokes on the following: https://github.com/Rotwood-Vale/Ratwood-Keep/blob/main/code/modules/antagonists/roguetown/villain/aspirant.dm#L37-L41 
With these errors: 
```
Error OD0001 at code/modules/antagonists/roguetown/villain/aspirant.dm:40:87: Expected ')' 
Error OD0001 at code/modules/antagonists/roguetown/villain/aspirant.dm:40:87: Expected end of proc statement
Error OD0001 at code/modules/antagonists/roguetown/villain/aspirant.dm:41:11: Expected end of proc statement
Warning OD0000 at code/modules/antagonists/roguetown/villain/aspirant.dm:43:3: Error recovery had to skip to code/modules/antagonists/roguetown/villain/aspirant.dm:43:8
```

Oddly enough the first error does *not* appear in the VSCode problems tab, making this extra confusing. Also note that:
```
if(!new_owner.assigned_role in GLOB.noble_positions || !new_owner.assigned_role in GLOB.garrison_positions) //broken
if(!(new_owner.assigned_role in GLOB.noble_positions || !new_owner.assigned_role) in GLOB.garrison_positions) //works
if(!(new_owner.assigned_role in GLOB.noble_positions) || !(new_owner.assigned_role in GLOB.garrison_positions))//works
```

### PR DESCRIPTION
**Pull request by wixoaGit**
Fixes #1958

`"a" in a || "b" in b` is not parsed as you would expect. It is treated as `("a" in (a || "b")) in b`. Our parser now reads it as this, as well as emits a warning to point out a potential issue in your code.

### CODE REVIEW

File: DMCompiler/Compiler/CompilerError.cs [hunk 1]
```diff
@@ -73,6 +73,7 @@ public enum WarningCode {
     SuspiciousSwitchCase = 3201, // "else if" cases are actually valid DM, they just spontaneously end the switch context and begin an if-else ladder within the else case of the switch
     AssignmentInConditional = 3202,
     PickWeightedSyntax = 3203,
+    AmbiguousInOrder = 3203
```
Comment (wixoaGit) [inline DMCompiler/Compiler/CompilerError.cs:76]:
```suggestion
    AmbiguousInOrder = 3204
```

File: Content.Tests/DMProject/Tests/Operators/In_OrderOfOperationsWarning.dm [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// COMPILE ERROR
+
+#pragma AmbiguousInOrder error
+
+/proc/RunTest()
+	if ("a" in list("a") && FALSE)
+		return true
```
Comment (wixoaGit) [inline Content.Tests/DMProject/Tests/Operators/In_OrderOfOperationsWarning.dm:7]:
```suggestion
		return TRUE
```
