### PR TITLE
Fully implement `/savefile` (except `ImportText()` because fuck it)

### LINKED ISSUE #1303: `/datum.Write(savefile)` is not implemented
```dm
/datum/foo
	var/bar = 15

/datum/foo/Write(savefile/S)
	ASSERT(bar == 15)

/proc/RunTest()
	var/datum/foo/F = new()
	var/savefile/S = new("foo_bar.sav")
	S << F
```

Emits
```
 Error OD0405 at write_override.dm:5:7: Definition for proc Write on type /datum/foo not found
 Compilation failed with 1 errors and 0 warnings
 Total time: 00:00
```

https://www.byond.com/docs/ref/#/datum/proc/Write

### LINKED ISSUE #1305: `/datum.Read(savefile)` is not implemented
https://www.byond.com/docs/ref/#/datum/proc/Read

It is defined, but not implemented

### LINKED ISSUE #1306: `savefile << object` is not implemented
https://www.byond.com/docs/ref/#/savefile/operator/%3c%3c

The file of interest is https://github.com/OpenDreamProject/OpenDream/blob/1b80c46ef2ffcabcd4e6cea0cffe52ac65fbc0b1/OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs#L8-L9

Which would need this implemented:
https://github.com/OpenDreamProject/OpenDream/blob/1b80c46ef2ffcabcd4e6cea0cffe52ac65fbc0b1/OpenDreamRuntime/Objects/DreamObject.cs#L383-L387

### PR DESCRIPTION
**Pull request by amylizzle**
`ExportText()`,  object reading & writing, calling `Read()` and `Write()`. Merged with #1546.

resolves #1303
resolves #1305
resolves #1306

Also fixed a bug with `fcopy()` where it'd fail if there wasn't a dir prefix like `./` 

## TODO
- [x] Implement ExportText()
- [x] ExportText for lists
- [x] Fix formatting on ExportText()
- [x] Finish saving objects under the weird ".0" path thing
- [x] Load objects, calling `New()` and `Read()`
- [x] Save/Load floats & strings
- [x] Save/Load lists
- [x] Lists with objects in them
- [x] Save/Load type paths
- [x] json serialisation & deserialisation 
- [x] filedata stuff (savefiles & icons)

### CODE REVIEW

File: OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs [hunk 1]
```diff
@@ -150,31 +164,372 @@ public sealed class SavefileDirectory : Dictionary<string, DreamValue> { }
...
+                    foreach(string key in storedObjectVars.Keys){
+                        if(key == "type")
+                            continue;
+                        resultObj.SetVariable(key, DeserializeJsonValue(storedObjectVars[key]));
+                    }
+                    resultObj.InitSpawn(new DreamProcArguments());
+                    resultObj.SpawnProc("Read", null, [new DreamValue(this)]);
+                    return new DreamValue(resultObj);
+                } else
+                    throw new InvalidDataException("Unable to deserialize object in savefile: " + ((storedObjectTypeJSON as SFDreamType) is null ? "no type specified (corrupted savefile?)" : "invalid type "+((SFDreamType)storedObjectTypeJSON!).TypePath));
```
Comment (LetterN) [inline OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs:325]: silently errors apparently
https://discord.com/channels/847318834952405042/887074737879138315/1200283136026755152

File: OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs [hunk 2]
```diff
@@ -118,15 +133,14 @@ public sealed class SavefileDirectory : Dictionary<string, DreamValue> { }
                 return true;
             case "dir":
                 DreamList dirList = ObjectTree.CreateList();
-
-                foreach (string dirPath in Directories.Keys) {
-                    if (dirPath.StartsWith(_currentDirPath)) {
-                        dirList.AddValue(new DreamValue(dirPath));
-                    }
-                }
+                // TODO reimplement
```
Comment (LetterN) [inline OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs:136]: loop CurrentDir keys, go deeper if children vals have keys

File: OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs [hunk 3]
```diff
@@ -150,31 +164,372 @@ public sealed class SavefileDirectory : Dictionary<string, DreamValue> { }
...
+            case DreamValue.DreamValueType.String:
+            case DreamValue.DreamValueType.Float:
+                return new SFDreamPrimitive { Value = val };
+            case DreamValue.DreamValueType.DreamType:
+                return new SFDreamType { TypePath = val.MustGetValueAsType().Path };
+            case DreamValue.DreamValueType.DreamResource:
+                var dreamResource = val.MustGetValueAsDreamResource();
+                return new SFDreamFileValue {
+                    Length = dreamResource.ResourceData!.Length,
+                    //Crc32 =  new System.IO.Hashing.Crc32().
```
Comment (LetterN) [inline OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs:352]: https://www.nuget.org/packages/System.IO.Hashing for crc, importtext might not align with the crc if its from byond which we could ignore

File: OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs (hunk 1 above)
Comment (amylizzle) [reply OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs:325]: well that's insane. How the hell is it inferring the type if type is overridden?
Honestly think this one should be an error.

Comment (amylizzle) [reply OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs:325]: Turns out the test case was bad, `F << S["foo"]` is a no-op. BYOND just silently fails and outputs a null. We choose to fail loudly instead.

File: OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs (hunk 2 above)
Comment (amylizzle) [reply OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs]: Resolved - afaict BYOND just dumps the directories in the current working directory, not subdirs. I have not implemented the save-backed list that would be needed for remove + add to work because I am so done. Added it as a TODO for later.

File: OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs (hunk 3 above)
Comment (amylizzle) [reply OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs]: Rolled my own, easier than importing a whole package.

File: OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs [hunk 4]
```diff
@@ -1,6 +1,10 @@
 ﻿using OpenDreamRuntime.Objects;
 using OpenDreamRuntime.Objects.Types;
+using OpenDreamRuntime.Resources;
```
Comment (wixoaGit) [inline OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs:3]: Unused
```suggestion
```

File: OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs [hunk 5]
```diff
@@ -1,6 +1,10 @@
...
 using DreamValueTypeFlag = OpenDreamRuntime.DreamValue.DreamValueTypeFlag;
+using System.IO;
+using System.Linq;
+using YamlDotNet.Core.Tokens;
```
Comment (wixoaGit) [inline OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs:7]: Unused
```suggestion
```

File: OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs [hunk 6]
```diff
@@ -9,29 +13,124 @@ internal static class DreamProcNativeSavefile {
...
+                throw new NotImplementedException($"Unhandled type {key} = {value} in ExportText()");
         }
 
-        if (!bundle.ResourceManager.TryLoadIcon(exportValue, out var icon)) {
-            throw new NotImplementedException("General support for ExportText() is not implemented");
+        if(string.IsNullOrEmpty(key) || key==".")
+            indent = -1; //don't indent the subdirs of directly accessed keys or root dir
+
+        foreach (string subkey in savefile.CurrentDir.Keys) {
+            savefile.CurrentPath = subkey;
```
Comment (wixoaGit) [inline OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs:94]: Rename to `subKey`
```suggestion
        foreach (string subKey in savefile.CurrentDir.Keys) {
            savefile.CurrentPath = subKey;
```

File: OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs [hunk 7]
```diff
@@ -9,29 +13,124 @@ internal static class DreamProcNativeSavefile {
...
+            case DreamObjectSavefile.SFDreamListValue listValue:
+                string result = "list(";
+
+                    for(int i=0; i<listValue.AssocKeys.Count; i++){
+                        if(listValue.AssocData != null && listValue.AssocData[i] != null)
+                            result += ExportTextInternalListFormat(listValue.AssocKeys[i])+" = "+ExportTextInternalListFormat(listValue.AssocData[i]!);
+                        else
+                            result += ExportTextInternalListFormat(listValue.AssocKeys[i]);
+                        result += ",";
+                    }
```
Comment (wixoaGit) [inline OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs:126]: This is over-indented
```suggestion
                   for(int i=0; i<listValue.AssocKeys.Count; i++){
                    if(listValue.AssocData != null && listValue.AssocData[i] != null)
                        result += ExportTextInternalListFormat(listValue.AssocKeys[i])+" = "+ExportTextInternalListFormat(listValue.AssocData[i]!);
                    else
                        result += ExportTextInternalListFormat(listValue.AssocKeys[i]);
                    result += ",";
                }
```

File: OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs [hunk 8]
```diff
@@ -9,29 +13,124 @@ internal static class DreamProcNativeSavefile {
...
+            case DreamObjectSavefile.SFDreamObjectPathValue objectValue:
+                result += $"{new string('\t', indent)}{key} = object(\"{objectValue.Path}\")\n";
+                break;
+            case DreamObjectSavefile.SFDreamType typeValue:
+                result += $"{new string('\t', indent)}{key} = {typeValue.TypePath}\n";
+                break;
+            case DreamObjectSavefile.SFDreamListValue listValue:
+                result += $"{new string('\t', indent)}{key} = {ExportTextInternalListFormat(listValue)}\n";
+                break;
+            case DreamObjectSavefile.SFDreamDir jsonValue:
```
Comment (wixoaGit) [inline OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs:80]: `jsonValue` is unused
```suggestion
            case DreamObjectSavefile.SFDreamDir:
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: Content.Tests/DMProject/Tests/Savefile/ExportText.dm [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+	P["subsavedir2"] = "butts"
+	P["subsavedir3"] = 123
+	
+	F["dir5"] = P
+	F["dir6/subdir6"] = 321
+	F["dir7"] = null
+	F["dirIcon"] = new /icon()
+	F["list"] << list("1",2,"three"=3,4, new /datum(), new /datum(), list(1,2,3, new /datum()))
+
+	ASSERT(F.dir ~= list("dir","dir2","dir3","dir4","dir5","dir6","dir7","dirIcon","list"))
```
[the remark this answers is not in the document]
Comment (amylizzle) [reply Content.Tests/DMProject/Tests/Savefile/ExportText.dm:26]: After a bit of investigation I have found that this *only* happens when a key is added like `F["dir/subdir"]`. In all other cases, the list is ordered alphabetically. I'm inclined to call this a BYOND bug honestly, and don't think we should implement it.

File: OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs [hunk 10]
```diff
@@ -140,41 +154,463 @@ public sealed class SavefileDirectory : Dictionary<string, DreamValue> { }
...
+            return DeserializeJsonValue(CurrentDir);
+        }
+
+        return DeserializeJsonValue(SeekTo(index, true)); //should create the path if it doesn't exist
+    }
+
+    public void RemoveSavefileValue(string index){
+        if (CurrentDir.Remove(index)) {
+            SavefilesToFlush.Add(this);
+            SavefilesToFlush.Add(this);
```
Comment (wixoaGit) [inline OpenDreamRuntime/Objects/Types/DreamObjectSavefile.cs:288]: Made a mistake in my suggestion
```suggestion
```

File: OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs [hunk 11]
```diff
@@ -9,29 +11,124 @@ internal static class DreamProcNativeSavefile {
...
+                }
+                throw new NotImplementedException($"Unhandled list entry type {listEntry} in ExportTextInternalListFormat()");
+            case DreamObjectSavefile.SFDreamObjectPathValue objectValue:
+                return $"object(\"{objectValue.Path}\")";
+            case DreamObjectSavefile.SFDreamType typeValue:
+                return $"{typeValue.TypePath}";
+            case DreamObjectSavefile.SFDreamListValue listValue:
+                string result = "list(";
+
+                   for(int i=0; i<listValue.AssocKeys.Count; i++){
```
Comment (wixoaGit) [inline OpenDreamRuntime/Procs/Native/DreamProcNativeSavefile.cs:118]: Another mistake
```suggestion
                for(int i=0; i<listValue.AssocKeys.Count; i++){
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]

**Review by wixoaGit — APPROVED** [review]
