### PR TITLE
Fix `loop` behaviour in `animate()`

### LINKED ISSUE #1791: `animate(loops=n)` doesn't work when animations are chained
setting `loops` should loop a whole chain of animations, not just the target one.

### PR DESCRIPTION
**Pull request by amylizzle**
Loop now properly works for chained animations.

Note that `animate()`s arg processing is still _fucked_ so it only works if you pass it as a named arg, not a positional one.

Fixes #1791

### CODE REVIEW

File: OpenDreamClient/Rendering/DreamIcon.cs [hunk 1]
```diff
@@ -47,6 +47,7 @@ internal sealed class DreamIcon(IGameTiming gameTiming, ClientAppearanceSystem a
     private int _animationFrame;
     private TimeSpan _animationFrameTime = gameTiming.CurTime;
     private List<AppearanceAnimation>? _appearanceAnimations;
+    private int _appearanceAnimationsLoops = 0;
```
Comment (amylizzle) [inline OpenDreamClient/Rendering/DreamIcon.cs:50]:
```suggestion
    private int _appearanceAnimationsLoops;
```

File: OpenDreamClient/Rendering/DreamIcon.cs [hunk 2]
```diff
@@ -89,7 +90,19 @@ internal sealed class DreamIcon(IGameTiming gameTiming, ClientAppearanceSystem a
                     start = _appearanceAnimations[^1].Start + _appearanceAnimations[^1].Duration; //if it's not parallel, it's chained
 
         _appearanceAnimations ??= new List<AppearanceAnimation>();
-        _appearanceAnimations.Add(new AppearanceAnimation(start, duration, endingAppearance, easing, loops, flags, delay));
+        if(_appearanceAnimations.Count == 0) {//only valid on the first animation
+            Logger.Debug("setting loops to {0}", loops);
```
Comment (amylizzle) [inline OpenDreamClient/Rendering/DreamIcon.cs:94]:
```suggestion

```

File: OpenDreamClient/Rendering/DreamIcon.cs [hunk 3]
```diff
@@ -133,7 +134,18 @@ internal sealed class DreamIcon(IGameTiming gameTiming, IClyde clyde, ClientAppe
...
+            _appearanceAnimationsLoops = loops;
+        }
+
+        for(int i=_appearanceAnimations.Count-1; i>=0; i--) //there can be only one last-in-sequence, and it might not be the last element of the list because it could be added to mid-loop
+            if(_appearanceAnimations[i].LastInSequence) {
+                var lastAnim =  _appearanceAnimations[i];
+                lastAnim.LastInSequence = false;
+                _appearanceAnimations[i] = lastAnim;
+                break;
+            }
```
Comment (amylizzle) [inline OpenDreamClient/Rendering/DreamIcon.cs:147]:
```suggestion
            }
            
```

**Review by wixoaGit — APPROVED** [review]
