### PR TITLE
Explicit expression wrapping in AST

### LINKED ISSUE #1225: Assign being treated as named argument
TG contains this code: `if(isnull((smoothing_groups = GLOB.bitflag_lists[txt_signature])))`

It causes the following runtime: `[ERRO] world.log: Exception occurred: /proc/isnull has no argument named smoothing_groups`

According to wixoa, the compiler is treating that as if the parentheses aren't there and it's a named argument.

### LINKED ISSUE #1276: Unable to dereference from `new`
```dm

/datum/foo
	var/bar = 5

/proc/RunTest()
	ASSERT((new/datum/foo()).bar == 5)
```

image

### PR DESCRIPTION
**Pull request by martinlyra**
- Fixes #1225 

Adds the `DMASTExpressionWrapping` which has no dedicated visitor; instead, it reroutes the visitor directly to the wrapped expression's own visitor instead. If this is undesirable, do let me know. This change does decommission `DMASTIdentifierWrapped` as it is functionally the same but with its own visitor.

### CODE REVIEW

**Comment by martinlyra** [comment]
Alright. After some more debugging, I was too quick to when I made the conclusion that #1267 was related to wrapping, when it was not.

File: DMCompiler/Compiler/DM/DMParser.cs [hunk 1]
```diff
@@ -1561,6 +1561,22 @@ public partial class DMParser : Parser<Token> {
...
+                    return new DMASTAssign(
+                        assignment.Location,
+                        new DMASTConstantNull(assignment.Location),
+                        assignment
+                    );
+                return wrapped;
+            }
+            return Expression();
+        }
+
```
Comment (martinlyra) [inline DMCompiler/Compiler/DM/DMParser.cs:1579]:
```suggestion
```

**Review by wixoaGit — APPROVED** [review]
