### PR TITLE
`exception.name` can be a datum

### LINKED ISSUE #1715: `exception.name` should support being not-a-string
per the DM ref (emphasis mine): `name: A text string (such as an error message) **or other value** `

essentially you can do `throw EXCEPTION(new /datum)` and have the resulting exception's `name` prop be that datum.

Naturally goon uses this.

### PR DESCRIPTION
**Pull request by amylizzle**
Fixes #1715

### CODE REVIEW

File: OpenDreamRuntime/DreamManager.cs [hunk 1]
```diff
@@ -330,10 +330,10 @@ public sealed partial class DreamManager {
...
             // Invoke world.Error()
             var obj =_objectTree.CreateObject<DreamObjectException>(_objectTree.Exception);
-            obj.Name = e.Message;
-            obj.Description = msg;
-            obj.Line = line;
-            obj.File = file;
+            obj.SetVariable("name", new DreamValue(e.Message));
+            obj.SetVariable("desc", new DreamValue(msg));
+            obj.SetVariable("file", new DreamValue(file));
+            obj.SetVariable("line", new DreamValue(line));
```
Comment (wixoaGit) [inline OpenDreamRuntime/DreamManager.cs:336]: Why go through the indirection of `SetVariable()` when we can set it directly?

File: OpenDreamRuntime/Objects/Types/DreamObjectException.cs [hunk 2]
```diff
@@ -1,17 +1,38 @@
...
+            case "file":
+                if(value.TryGetValueAsString(out var stringFile))
+                    File = stringFile;
+                break;
+            case "line":
+                if(value.TryGetValueAsInteger(out var intLine))
+                    Line = intLine;
+                break;
+        }
+        base.SetVar(varName, value);
```
Comment (wixoaGit) [inline OpenDreamRuntime/Objects/Types/DreamObjectException.cs:29]: `base.SetVar()` should only be called in the default case of the above switch. This is because it will add any variables it doesn't recognize to the object's list of modified variables. This is unnecessary when it will never be used.

File: OpenDreamRuntime/Objects/Types/DreamObjectException.cs [hunk 3]
```diff
@@ -1,17 +1,38 @@
...
     //TODO: Match the format of BYOND exceptions since SS13 does splittext and other things to extract data from exceptions
 
+    protected override void SetVar(string varName, DreamValue value) {
+        switch (varName) { //set the internal vars of the C# object, then pass through to base.setvar to handle DM side
+            case "name":
+                Name = value;
+                break;
+            case "desc":
+                if(value.TryGetValueAsString(out var stringDescription))
+                    Description = stringDescription;
```
Comment (wixoaGit) [inline OpenDreamRuntime/Objects/Types/DreamObjectException.cs:18]: This doesn't have to be a string in BYOND. It will take any value, with DreamObject types (that aren't lists) being turned into their display name, `DreamObject.GetDisplayName()`.

Same with `file` and `line`

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: OpenDreamRuntime/Objects/Types/DreamObjectException.cs [hunk 4]
```diff
@@ -1,26 +1,47 @@
...
+                return;
+            case "desc":
+                Desc = value;
+                return;
+            case "file":
+                File = value;
+                return;
+            case "line":
+                Line = value;
+                return;
```
Comment (wixoaGit) [inline OpenDreamRuntime/Objects/Types/DreamObjectException.cs:24]: This misses the part where DreamObjects that aren't lists will instead use that object's `GetDisplayName()`

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: OpenDreamRuntime/Objects/Types/DreamObjectException.cs (hunk 4 above)
Comment (wixoaGit) [reply OpenDreamRuntime/Objects/Types/DreamObjectException.cs:24]: Ignore me, misunderstood the output of `json_encode()`
