### PR TITLE
Rewrite DMObjectBuilder to be based off a code tree, fix global init order, other fixes

### LINKED ISSUE #778: Children types declared before parent ones can have clobbering var declarations without error
Kind of a wordy title, sorry, but the gist is that this:
```dm
/atom/var/bluh
/datum/var/bluh
```
currently compiles without any errors, even though the former definition is clobbering the latter.

Oversight of #771 (although this problem existed before that PR)

Putting up an issue instead of just instantly fixing it like the chad I am because it actually is a symptom of a greater issue surrounding how to efficiently handle the fact that variable & type definitions can occur in any order in this language.

### LINKED ISSUE #2040: TGMC: Bad init order causes `/datum/browser` to break
`/datum/browser` has this var: `var/static/datum/asset/simple/namespaced/common/common_asset = get_asset_datum(/datum/asset/simple/namespaced/common)`

`get_asset_datum()` essentially checks a `GLOB` list or instantiates the arg type if it doesn't exist in the list yet.

The problem is that OpenDream is initializing this static variable, and thus the proc call, before `GLOB` has been instantiated by the world genesis proc. This causes the browser datum to break entirely.

### LINKED ISSUE #2041: In BYOND, type declaration compile order impacts static var initialization order
This is the root cause of https://github.com/OpenDreamProject/OpenDream/issues/2040

The compile order of types impacts the order of their static var initialization:

Case 1:
```
var/global/datum/controller/global_vars/GLOB;

/datum/browser
    var/static/datum/asset/simple/namespaced/common/common_asset = get_asset_datum(/datum/asset/simple/namespaced/common)

/world/proc/Genesis()
    world.log << "Genesis"
    GLOB = new
    GLOB.InitGlobalasset_datums()

/datum/controller/global_vars/var/global/list/asset_datums; /datum/controller/global_vars/proc/InitGlobalasset_datums(){asset_datums = list();}
/proc/get_asset_datum(type)
    world.log << "get_asset_datum"
    var/datum/asset/loaded_asset = GLOB.asset_datums[type] || new type()
    return loaded_asset.ensure_ready()

/datum/asset/proc/ensure_ready()
    return src
    
/datum/asset/simple/namespaced/common

/proc/main()

/world/Error(e)
    world.log << e

/world/proc/_()
    var/static/_ = world.Genesis()
```
image

Case 2 (note the type declarations):
```
var/global/datum/controller/global_vars/GLOB;

/world

/datum/browser
    var/static/datum/asset/simple/namespaced/common/common_asset = get_asset_datum(/datum/asset/simple/namespaced/common)

/world/proc/Genesis()
    world.log << "Genesis"
    GLOB = new
    GLOB.InitGlobalasset_datums()

/datum/controller/global_vars/var/global/list/asset_datums; /datum/controller/global_vars/proc/InitGlobalasset_datums(){asset_datums = list();}
/proc/get_asset_datum(type)
    world.log << "get_asset_datum"
    var/datum/asset/loaded_asset = GLOB.asset_datums[type] || new type()
    return loaded_asset.ensure_ready()

/datum/asset/proc/ensure_ready()
    return src
    
/datum/asset/simple/namespaced/common

/proc/main()

/world/Error(e)
    world.log << e

/world/proc/_()
    var/static/_ = world.Genesis()
```
image

### PR DESCRIPTION
**Pull request by wixoaGit**
Finally got a working model of how global init order works in BYOND. This is a good-enough first implementation of it. The init order this produces works in tg, goonstation, and paradise.

This definitely needs more explanation & documentation but at the moment I'm way too fatigued on this.

Fixes #2041
Fixes #2040 
Fixes #778 (~~Unsure if this is what fixed it, but it is fixed~~ Revealed a duplicate var error in one of our tests, so it's fixed)

### CODE REVIEW

File: DMCompiler/DM/Builders/DMExpressionBuilder.cs [hunk 1]
```diff
@@ -15,262 +15,343 @@ public enum ScopeMode {
...
 
         /// Only global procs available
-        FirstPassStatic,
+        FirstPassStatic
     }
 
     // TODO: Remove these terrible global flags
     public static ScopeMode CurrentScopeMode = ScopeMode.Normal;
-    public static bool ScopeOperatorEnabled = false; // Enabled once var overrides have been processed
+    public static bool ScopeOperatorEnabled = false; // Enabled after the first pass of the code tree
```
Comment (wixoaGit) [inline DMCompiler/DM/Builders/DMExpressionBuilder.cs:23]:
```suggestion
    public static bool ScopeOperatorEnabled = false; // Enabled on the last pass of the code tree
```
