### PR TITLE
Fix modifiers as keybinds, add ".winset :type" support

### LINKED ISSUE #1936: `.winset :map` is not implemented
```
macro "default"
    elem ".winset :map.right-click=false"
        name = "SHIFT+Shift"
    elem "Shift"
        name = "SHIFT"
        command = ".winset :map.right-click=false"
    elem "ShiftUp"
        name = "SHIFT+UP"
        command = ".winset :map.right-click=true"
```

This is needed for TG Shift+RMB behavior, which just causes the context menu to appear by temporarily disabling the `right-click` parameter.

### PR DESCRIPTION
**Pull request by ike709**
Resolves #1936 

- In the DMF, modifier keys are now treated as keys when no other key is present. This appears to be more in line with the behavior described in the ref.
- `.winset :[type].whatever` is now implemented, where `:[type]` is the default control of that type

This makes TG shift+RMB behavior functional.

RMB toggles the cabinet's open/closed state. Shift+RMB opens ye olde context menu.

https://github.com/user-attachments/assets/c4a3949a-c088-4f12-9aeb-764bb8b5227c

### CODE REVIEW

File: OpenDreamClient/Interface/DreamInterfaceManager.cs [hunk 1]
```diff
@@ -302,7 +302,7 @@ public void FrameUpdate(FrameEventArgs frameEventArgs) {
             DefaultMap.Viewport.Eye = _eyeManager.CurrentEye;
     }
 
-    public InterfaceElement? FindElementWithId(string id) {
+    public InterfaceElement? FindElementWithId(string id, bool selectDefault = false) {
```
Comment (wixoaGit) [inline OpenDreamClient/Interface/DreamInterfaceManager.cs:305]: There are a lot of calls to `FindElementWithId()` that would need to explicitly set `selectDefault`. I think it's better to instead have the colon be a part of `id` so it works more universally.

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: OpenDreamClient/Interface/DreamInterfaceManager.cs [hunk 2]
```diff
@@ -330,6 +330,20 @@ public void FrameUpdate(FrameEventArgs frameEventArgs) {
         } else {
             string elementId = split[0];
 
+            // ":[element]" returns the default element of that type
+            if (elementId[0] == ':') {
+                switch (elementId[1..]) {
```
Comment (wixoaGit) [inline OpenDreamClient/Interface/DreamInterfaceManager.cs:335]: You were worried about the string operation, right? You could just put `:` at the beginning of each case instead

**Review by wixoaGit — APPROVED** [review]
