### PR TITLE
Fix isnull

### LINKED ISSUE #1638: `isnull(deleted object)` returns `0`
It should return `1`

```
var/obj/O = new()
del(O)
world.log << "[json_encode(O)] [json_encode(isnull(O))]"
```

BYOND: `null 1`
OD: `null 0`

### PR DESCRIPTION
**Pull request by amylizzle**
Fixes #1638

### CODE REVIEW

File: OpenDreamRuntime/DreamValue.cs [hunk 1]
```diff
@@ -108,7 +108,7 @@ public enum DreamValueTypeFlag {
 
         public bool IsNull {
             [MethodImpl(MethodImplOptions.AggressiveInlining)]
-            get => Type == DreamValueType.DreamObject && _refValue == null;
+            get => Type == DreamValueType.DreamObject && (_refValue == null || ((DreamObject) _refValue).Deleted);
```
Comment (ike709) [inline OpenDreamRuntime/DreamValue.cs:111]: Since we're already checking Type you can probably use `Unsafe.As` to avoid a typecast on every `IsNull` call

**Review by wixoaGit — APPROVED** [review]
