### PR TITLE
Fix static vars trying to reference local vars, and add pragma

### LINKED ISSUE #997: In BYOND, RHS of Static Vars Can Only Access `world` Vars
Consider this code:
```
/world
    name = "wew lad"

var/global/name = "wumbo"

/obj
    name = "meep"
/obj/proc/bar()
    var/static/L = name
    world.log << L
/proc/main()
    (new /obj()).bar()
```
What do you think it prints? The answer is `"wew lad"` because `var/static/L = name` is actually `var/static/L = world.name` in BYOND.

### PR DESCRIPTION
**Pull request by SaphireLattice**
Pragma `OD2212` triggers as an error when the code accesses a global var while there's an identically named local one

Closes #997

### CODE REVIEW

File: DMCompiler/DM/Builders/DMExpressionBuilder.cs [hunk 1]
```diff
@@ -554,13 +554,16 @@ private static DMExpression BuildIdentifier(DMASTIdentifier identifier, DMObject
...
-                if (field != null) {
+                if (field != null && CurrentScopeMode == ScopeMode.Normal) {
                     return new Field(identifier.Location, field, field.ValType);
                 }
 
                 var globalId = proc?.GetGlobalVariableId(name) ?? dmObject.GetGlobalVariableId(name);
 
                 if (globalId != null) {
+                    if (field is not null)
+                        DMCompiler.Emit(WarningCode.AmbiguousVarStatic, identifier.Location, $"Static var definition can not reference instance variable \"{name}\" but a global exists");
```
Comment (wixoaGit) [inline DMCompiler/DM/Builders/DMExpressionBuilder.cs:565]:
```suggestion
                        DMCompiler.Emit(WarningCode.AmbiguousVarStatic, identifier.Location, $"Static var definition cannot reference instance variable \"{name}\" but a global exists");
```

File: DMCompiler/DMStandard/DefaultPragmaConfig.dm [hunk 2]
```diff
@@ -32,6 +32,7 @@
 #pragma SuspiciousSwitchCase warning
 #pragma PointlessPositionalArgument warning
 #pragma ProcArgumentGlobal warning // Ref BYOND issue https://www.byond.com/forum/post/2830750
+#pragma AmbiguousVarStatic error // https://github.com/OpenDreamProject/OpenDream/issues/997
```
Comment (wixoaGit) [inline DMCompiler/DMStandard/DefaultPragmaConfig.dm:35]: I think this should be a notice by default. When a static of the same name exists it's fine to use that.

When I said it should be an error, I was thinking of situations where there was only an instance variable with the name.
```suggestion
#pragma AmbiguousVarStatic notice // https://github.com/OpenDreamProject/OpenDream/issues/997
```

File: DMCompiler/Compiler/CompilerError.cs [hunk 3]
```diff
@@ -50,6 +50,7 @@ public enum WarningCode {
     PointlessScopeOperator = 2209,
     PointlessPositionalArgument = 2210,
     ProcArgumentGlobal = 2211, // Prepending "/" on a proc arg (e.g. "/proc/example(/var/foo)" makes the arg a global var. Ref https://www.byond.com/forum/post/2830750
+    AmbiguousVarStatic = 2212, // Assigning an instance variable to a static one (which gives unknown ref) while a global exists (which makes it work, with unexpected value)
```
Comment (wixoaGit) [inline DMCompiler/Compiler/CompilerError.cs:53]:
```suggestion
    AmbiguousVarStatic = 2212, // Referencing a static variable when an instance variable with the same name exists
```

**Review by wixoaGit — CHANGES_REQUESTED** [review]

File: DMCompiler/DMStandard/DefaultPragmaConfig.dm (hunk 2 above)
Comment (SaphireLattice) [reply DMCompiler/DMStandard/DefaultPragmaConfig.dm:35]: I think if a codebase needs to use ambiguous names like this, they could do this on their own. Otherwise it prevents awful footguns.

The thing didn't trigger on Paradise at all. Not sure about other codebases though.

Comment (wixoaGit) [reply DMCompiler/DMStandard/DefaultPragmaConfig.dm:35]: The general philosophy with these pragmas has been to not error on things that byond doesn't. If a codebase wants the extra guarantee of erroring on it, they can raise it themselves (as they've been doing up to now).

I said `notice` because I felt it was a little pedantic of a lint, but I can see a case being made for `warning`.

Comment (SaphireLattice) [reply DMCompiler/DMStandard/DefaultPragmaConfig.dm:35]: Ah, I see. 

Probably want a pedantic mode in compiler that uses harsher pragmas, eventually

Probably should be a warning. It's gonna be pretty ambiguous when trying to read it unless you keep this behavior in mind.

**Review by wixoaGit — APPROVED** [review]
