### PR TITLE
Add `name` to `IconAppearance`, fix placeholder turf names

### LINKED ISSUE #1960: Context menu shows a placeholder name for turfs
Turfs are supported in the right-click context menu as of https://github.com/OpenDreamProject/OpenDream/pull/1951. However, all turfs use a placeholder name of `turf (OD WIP)`. To resolve this, the `Name` field needs to be re-added to `IconAppearance` so clients are aware of turf names.

### PR DESCRIPTION
**Pull request by ike709**
Resolves #1960 

As far as I can tell it seems to work?

image

### CODE REVIEW

File: OpenDreamRuntime/AtomManager.cs [hunk 1]
```diff
@@ -241,6 +242,9 @@ public bool IsValidAppearanceVar(string name) {
 
     public void SetAppearanceVar(IconAppearance appearance, string varName, DreamValue value) {
         switch (varName) {
+            case "name":
+                value.TryGetValueAsString(out appearance.Name);
```
Comment (wixoaGit) [inline OpenDreamRuntime/AtomManager.cs:246]: This will set `appearance.Name` to `null` if the value isn't a string.

File: OpenDreamShared/Dream/IconAppearance.cs [hunk 2]
```diff
@@ -58,6 +69,7 @@ public sealed class IconAppearance : IEquatable<IconAppearance> {
     ];
 
     public IconAppearance() {
+        Name = string.Empty;
```
Comment (wixoaGit) [inline OpenDreamShared/Dream/IconAppearance.cs:72]: You should follow the pattern and put this in the field definition instead (`public string Name = string.Empty`)

File: OpenDreamShared/Network/Messages/MsgAllAppearances.cs [hunk 3]
```diff
@@ -217,6 +221,9 @@ public override void WriteToBuffer(NetOutgoingMessage buffer, IRobustSerializer
 
             lastId = pair.Key;
 
+            buffer.Write((byte)Property.Name);
+            buffer.Write(appearance.Name);
```
Comment (wixoaGit) [inline OpenDreamShared/Network/Messages/MsgAllAppearances.cs:225]: You could avoid writing this property if it's equal to `IconAppearance.Default.Name`

**Review by wixoaGit — CHANGES_REQUESTED** [review]

**Review by wixoaGit — APPROVED** [review]
